M48
; DRILL file {KiCad 7.0.5} date Wed Oct  4 22:36:44 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-04T22:36:44-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0550
%
G90
G05
T1
X4.48Y-2.3724
X4.48Y-2.4511
T2
X3.055Y-2.35
X3.055Y-2.45
X4.71Y-2.35
X4.71Y-2.45
T3
X3.27Y-2.0
X3.27Y-2.3
X3.27Y-2.5
X4.07Y-2.0
X4.07Y-2.4
X4.07Y-2.8
T0
M30
