M48
; DRILL file {KiCad 7.0.5} date Wed Oct  4 22:36:44 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-04T22:36:44-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1160
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X2.75Y-2.0
X2.75Y-2.8
X5.0Y-2.0
X5.0Y-2.8
T2
X2.7148Y-2.4951
X2.715Y-2.305
X5.05Y-2.495
X5.0502Y-2.3049
T0
M30
